title: Site

columns:
  - width: 2/3
    sections:
      pages:
        type: pages
        headline: Pages
        parent: site.find("pages")
        status: all
        template: page
      meta:
        type: fields
        fields:
          copyright:
            type: textarea
            label: Pied de page
  - width: 1/3
    sections:
      sub:
        type: pages
        headline: Pages
        status: all
        templates:
          - home
          - error
          - pages